---
version: 2
jobs:
  build:
    working_directory: ~/cca
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: cca
          RAILS_ENV: test
      - image: postgres:9.6
        environment:
          POSTGRES_USER: cca
          POSTGRES_DB: cca_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: cca-bundle-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run:
          name: Bundle install
          command: bundle check || bundle install

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: cca-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - type: cache-restore
        name: Restore Yarn cache
        key: cca-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - type: cache-save
        name: Store Yarn cache
        key: rails-demo-yarn-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the database
      - run: bin/rails db:setup

      # Compile assets
      - run: bin/rails webpacker:compile

      # Run the tests
      - run: bin/rails test
      - run: bin/rails test:system
