---
development:
  host: 'development.archicc.com'
  secret_key_base: 51ae4eeb16139a4fb452d54601286c300f55e1544e12614efe88cd082c6d79d9d7e39eba05cf509660a4b68050273d34c660424abaed422f73d88de138e711ec
  system_from_email: 'Cabinet CCA <no-reply@example.com>'
  aws_s3_access_key_id: <%= ENV['AWS_S3_ACCESS_KEY_ID'] %>
  aws_s3_secret_access_key: <%= ENV['AWS_S3_SECRET_ACCESS_KEY'] %>
  aws_s3_region: <%= ENV['AWS_S3_REGION'] %>
  aws_s3_bucket: <%= ENV['AWS_S3_BUCKET'] %>

test:
  host: 'test.archicc.com'
  secret_key_base: ec2487d41e30799759dec4e3b01ddace347d1c9c2bd2d42b3daa227752d66613cd6c76f136b22ad4b33f31c2d3a931f016c635380361705fa36ee2fa1c1ef401
  system_from_email: 'Cabinet CCA <no-reply@example.com>'

production:
  host: <%= ENV['HOST'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>
  system_from_email: "Cabinet CCA <%= ENV['SYSTEM_FROM_EMAIL'] %>"
  aws_s3_access_key_id: <%= ENV['AWS_S3_ACCESS_KEY_ID'] %>
  aws_s3_secret_access_key: <%= ENV['AWS_S3_SECRET_ACCESS_KEY'] %>
  aws_s3_region: <%= ENV['AWS_S3_REGION'] %>
  aws_s3_bucket: <%= ENV['AWS_S3_BUCKET'] %>
