---
default: &default
  host: <%= ENV['HOST'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  system_from_email: "Cabinet CCA <%= ENV['SYSTEM_FROM_EMAIL'] %>"
  aws_s3_access_key_id: <%= ENV['AWS_S3_ACCESS_KEY_ID'] %>
  aws_s3_secret_access_key: <%= ENV['AWS_S3_SECRET_ACCESS_KEY'] %>
  aws_s3_region: <%= ENV['AWS_S3_REGION'] %>
  aws_s3_bucket: <%= ENV['AWS_S3_BUCKET'] %>

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>
